site_name: STEMAIDE Docs
site_description: Documentation for STEMAIDE, a platform for STEMAIDE Coder Manual.
site_author: STEMAIDE
site_dir: site
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  logo: assets/stemaide-logo-white-footer.128px.webp
  favicon: assets/favicon.ico
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - search.highlight
    - search.suggest
    - toc.integrate
    - navigation.footer

# hooks:
#   - hooks.py

plugins:
  - search

validation:
  nav:
    omitted_files: ignore
    not_found: ignore
    absolute_links: ignore
  links:
    not_found: ignore
    anchors: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/nav.js

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/stemaideafrica
      name: Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/stemaide
      name: Facebook
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/stemaideafrica
      name: X (Twitter)
    - icon: fontawesome/brands/whatsapp
      link: https://www.whatsapp.com/channel/0029VaCyaNN5a23vbdCABI0n
      name: WhatsApp
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@STEMAIDEAfrica
      name: YouTube
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@stemaide
      name: TikTok

nav:
  - Home: index.md
  - Getting Started:
    #   - Introduction: STEMAIDE_CODER_Kit_Manual/Getting Started/Introduction.md
      - Arduino IDE Setup: STEMAIDE_CODER_Kit_Manual/Getting Started/Arduino_IDE_Setup.md
      - Basic Programming Concepts: STEMAIDE_CODER_Kit_Manual/Getting Started/Basic_Programming_Concept.md
      - Safety Guidelines: STEMAIDE_CODER_Kit_Manual/Getting Started/Safety_Guidelines.md
  - Beginner Projects:
      - Overview: STEMAIDE_CODER_Kit_Manual/Beginner Projects/index.md
      - 1.1 LED Control:
          - 1.1.1 Turn ON One LED: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.1_Turn_ON_One_LED.md
          - 1.1.2 Blink One LED: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.2_Blink_One_LED.md
          - 1.1.3 Turn ON Two LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.3_Turn_ON_Two_LEDs.md
          - 1.1.4 Blink Two LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.4_Blink_Two_LEDs.md
          - 1.1.5 Turn ON Three LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.5_Turn_ON_Three_LEDs.md
          - 1.1.6 Blink Three LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.6_Blink_Three_LEDs.md
          - 1.1.7 Turn ON Four LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.7_Turn_ON_Four_LEDs.md
          - 1.1.8 Blink Four LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.8_Blink_Four_LEDs.md
          - 1.1.9 Turn ON Five LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.9_Turn_ON_Five_LEDs.md
          - 1.1.10 Blink Five LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.1_LED/1.1.10_Blink_Five_LEDs.md
      - 1.2 Buzzer:
          - 1.2.1 Buzzer ON/OFF: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.2_Buzzer/1.2.1_Buzzer_ON_OFF.md
          - 1.2.2 Buzzer Beep: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.2_Buzzer/1.2.2_Buzzer_Beep.md
          - 1.2.3 Piezo Beep Code Generator: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.2_Buzzer/1.2.3_Piezo_Beep_Code_Generator.md
      - 1.3 Push Button:
          - 1.3.1 Button with 1 LED: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.3_Push_Button/1.3.1_Button_With_1_LED.md
          - 1.3.2 Button with 2 LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.3_Push_Button/1.3.2_Button_With_2_LEDs.md
          - 1.3.3 Button with 3 LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.3_Push_Button/1.3.3_Button_With_3_LEDs.md
          - 1.3.4 Button with 4 LEDs: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.3_Push_Button/1.3.4_Button_With_4_LEDs.md
      - 1.4 Traffic Light Module:
          - 1.4.1 Green Light ON: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.4_Traffic_Light_Module/1.4.1_Green_Light_ON.md
          - 1.4.2 Blink Green Light: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.4_Traffic_Light_Module/1.4.2_Blink_Green_Light.md
          - 1.4.3 Red Light ON: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.4_Traffic_Light_Module/1.4.3_Red_Light_ON.md
          - 1.4.4 Blink Red Light: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.4_Traffic_Light_Module/1.4.4_Blink_Red_Light.md
          - 1.4.5 Yellow Light ON: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.4_Traffic_Light_Module/1.4.5_Yellow_Light_ON.md
          - 1.4.6 Blink Yellow Light: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.4_Traffic_Light_Module/1.4.6_Blink_Yellow_Light.md
      - 1.5 RGB Module:
          - 1.5.1 RGB Introduction: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.0_RGB_Introduction.md
          - 1.5.2 Red ON: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.1_Red_ON.md
          - 1.5.3 Red Blink: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.2_Red_Blink.md
          - 1.5.4 Green ON: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.3_Green_ON.md
          - 1.5.5 Green Blink: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.4_Green_Blink.md
          - 1.5.6 Blue ON: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.5_Blue_ON.md
          - 1.5.7 Blue Blink: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.6_Blue_Blink.md
          - 1.5.8 Rainbow Colors: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.5_RGB_Module/1.5.7_Rainbow_Colors.md
      - 1.6 LDR Module: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.6_LDR_Module/1.6.1_LDR_Module.md
      - 1.7 Servo Motor:
          - 1.7.1 One Angle: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.7_Servo_Motor/1.7.1_One_Angle.md
          - 1.7.2 Sweep: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.7_Servo_Motor/1.7.2_Sweep.md
      - 1.8 Ultrasonic Sensor:
          - 1.8.1 Ultrasonic Sensor with RGB: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.8_Ultrasonic_Sensor/1.8.1_Ultrasonic_With_RGB.md
          - 1.8.2 Ultrasonic Distance Monitor: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.8_Ultrasonic_Sensor/1.8.2_Ultrasonic_Distance_Monitor.md
      - 1.9 Sound Sensor: 
          - 1.9.1 Noise Checker: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.9_Sound_Sensor/1.9.1_Sound_Sensor.md
          - 1.9.2 Sound Level Trigger: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.9_Sound_Sensor/1.9.2_Sound_Level_Trigger.md
      - 1.10 Noise Level Alarm:
         - 1.10 Noise Level Alarm: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.10_Noise_Level_Alarm/1.10.1_Noise_level_alarm.md
      - 1.11 Smart Simulation Night/Day Light:
         - 1.11 Solar Simulation Night/Day Light: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.11_Solar_Simulation/1.11.1_solar_simulated.md
      - 1.12 Smart Potentiometer Dimmer:
         - 1.12 Smart Potentiometer Dimmer: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.12_Smart_potentiometer_dimmer/1.12.1_smart_potentiometer.md
         - 1.12.2 Analog Dial Positioner: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.12_Smart_potentiometer_dimmer/1.12.2_Analog_Dial_Positioner.md
      - 1.13 Smart RGB Selector:
         - 1.13.1 Smart RGB Selector: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.13_Push_Button_RGB_Selector/1.13.1_push_button_rgb_selector.md
         - 1.13.2 Serial Button Terminal: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.13_Push_Button_RGB_Selector/1.13.2_Serial_Button_Terminal.md
      - 1.14 Smart Servo Controlled Drawbridge:
         - 1.14 Smart Servo Controlled Drawbridge: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.14_Servo_Controlled_Drawbridge/1.14.1_servo_controlled_drawbridge.md
      - 1.15 Smart Distance Based Led Brighness:
         - 1.15 Smart Distance Based Led Brighness: STEMAIDE_CODER_Kit_Manual/Beginner Projects/1.15_Distance_Based_Led_Brightness/1.15.1_distance_based_led.md
  - Intermediate Projects:
      - Overview: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/index.md
      - 2.1 Button and Buzzer: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.1_Button_And_Buzzer/2.1.1_Button_And_Buzzer.md
      - 2.2 Button and RGB: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.2_Button_And_RGB/2.2.1_Button_And_RGB.md
      - 2.3 Button and Traffic Light: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.3_Button_And_Traffic_Light/2.3.1_Button_And_Traffic_Light.md
      - 2.4 LDR and RGB: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.4_LDR_And_RGB/2.4.1_LDR_And_RGB.md
      - 2.5 Light Dependent Resistor:
        - 2.5.1 LDR and Traffic Light: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.5_LDR_And_Traffic_Light/2.5.1_LDR_And_Traffic_Light.md
        - 2.5.2 Solar Sensing Streetlight: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.5_LDR_And_Traffic_Light/2.5.2_Solar_Sensing_Streetlight.md
        - 2.5.3 Light_Sensitive_Canopy_Controller: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.5_LDR_And_Traffic_Light/2.5.3_Light_Sensitive_Canopy_Controller.md
      - 2.6 Ultrasonic and Buzzer: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.6_Ultrasonic_And_Buzzer/2.6.1_Ultrasonic_And_Buzzer.md
      - 2.7 Ultrasonic and RGB: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.7_Ultrasonic_And_RGB/2.7.1_Ultrasonic_And_RGB.md
      - 2.8 Sound Sensor and Traffic Light: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.8_Sound_Sensor_And_Traffic_Light/2.8.1_Sound_Sensor_And_Traffic_Light.md
      - 2.9 Servo and Ultrasonic: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.9_Servo_And_Ultrasonic/2.9.1_Servo_And_Ultrasonic.md
      - 2.10 Smart Alarm Projects:
          - Ultrasonic + LED:
              - Ultrasonic with 1 LED: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Ultrasonic_LED/2.10.1_Ultrasonic_with_1_LED.md
              - Ultrasonic with 2 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Ultrasonic_LED/2.10.2_Ultrasonic_with_2_LEDs.md
              - Ultrasonic with 3 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Ultrasonic_LED/2.10.3_Ultrasonic_with_3_LEDs.md
              - Ultrasonic with 4 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Ultrasonic_LED/2.10.4_Ultrasonic_with_4_LEDs.md
          - Push Button + LED:
              - Button to Control LED: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Push_Button_LED/2.10.5_Button_to_control_LED.md
              - Button to Blink LED: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Push_Button_LED/2.10.6_Button_to_blink_LED.md
              - Button to Control 2 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Push_Button_LED/2.10.7_Button_to_control_2_LEDs.md
              - Button to Blink 2 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Push_Button_LED/2.10.8_Button_to_blink_2_LEDs.md
              - Button to Control 3 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Push_Button_LED/2.10.9_Button_to_control_3_LEDs.md
              - Button to Blink 4 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Push_Button_LED/2.10.10_Button_to_blink_4_LEDs.md
          - LDR + LED:
              - LDR with 1 LED: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/LDR_LED/2.10.11_LDR_with_1_LED.md
              - LDR with 2 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/LDR_LED/2.10.12_LDR_with_2_LEDs.md
              - LDR with 4 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/LDR_LED/2.10.13_LDR_with_4_LEDs.md
              - LDR with 5 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/LDR_LED/2.10.14_LDR_with_5_LEDs.md
          - LDR + Buzzer: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/LDR_Buzzer/2.10.15_LDR_with_Buzzer.md
          - Sound + LED:
              - Sound with 1 LED: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Sound_LED/2.10.16_Sound_with_1_LED.md
              - Sound with 2 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Sound_LED/2.10.17_Sound_with_2_LEDs.md
              - Sound with 3 LEDs: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.10_Smart_Alarm_Projects/Sound_LED/2.10.18_Sound_with_3_LEDs.md
      - 2.11 Potentiometer Buzzer: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.11_Potentiometer_Buzzer/2.111_Potentiometer_Buzzer.md
      - 2.12 Automatic traffic detention: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.12_Automatic_traffic_detention/2.12.1_Automatic_traffic_detention.md
      - 2.13 Intruder Alarm System: STEMAIDE_CODER_Kit_Manual/Intermediate Projects/2.13_Intruder_Alarm_System/2.13.1_Automatic_traffic_detention.md
  - Advanced Projects:
      - Overview: STEMAIDE_CODER_Kit_Manual/Advance Projects/index.md
      - 3.1 Automatic Curtain Controller: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.1_Automatic_Curtain_Controller/3.1.1_Automatic_Curtain_Controller.md
      - 3.2 Smart Parking System: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.2_Smart_Parking_System/3.2.1_Smart_Car_Parking_System.md
      - 3.3 Home Security System: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.3_Home_Security_System/3.3.1_Smart_Security_System.md
      - 3.4 Security Gate Audio Alert: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.4_Security_Gate_Audio_Alert/3.4.1_Security_Gate_Audio_Alert.md
      - 3.5 Smart Traffic Light System: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.5_Smart_Traffic_Light_System/3.5.1_Smart_Traffic_Light_System.md
      - 3.6 STEM Capstone Projects:
          - 3.6.1 Smart Gauge System: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.6_STEM_Capstone_Projects/3.6.1_Smart_Gauge_System.md
          - 3.6.2 Smart Traffic Light System: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.6_STEM_Capstone_Projects/3.6.2_Smart_Traffic_Light_System.md
      - 3.7 Sound Controlled Desk Lamp: STEMAIDE_CODER_Kit_Manual/Advance Projects/3.7_Sound_Controlled_Desk_Lamp/3.7.1_Sound_Controlled_Desk_Lamp.md
  - Appendices:
    #   - Overview: STEMAIDE_CODER_Kit_Manual/Appendices/index.md
      - Wiring Reference: STEMAIDE_CODER_Kit_Manual/Appendices/Wiring_Reference.md
      - Common Errors: STEMAIDE_CODER_Kit_Manual/Appendices/Common_Errors.md
      - Component Guide: STEMAIDE_CODER_Kit_Manual/Appendices/Component_Guide.md
      - Troubleshooting: STEMAIDE_CODER_Kit_Manual/Appendices/Troubleshooting.md
    #   - User Guide: STEMAIDE_CODER_Kit_Manual/Appendices/User_Guide.md
    #   - Developer Guide: STEMAIDE_CODER_Kit_Manual/Appendices/Developer_Guide.md
    #   - Core Features: STEMAIDE_CODER_Kit_Manual/Appendices/Core_Features.md
    #   - Advanced Features: STEMAIDE_CODER_Kit_Manual/Appendices/Advanced_Features.md
    #   - About Prol: STEMAIDE_CODER_Kit_Manual/Appendices/About_Prol.md
      - Code of Conduct: STEMAIDE_CODER_Kit_Manual/Appendices/Code_of_Conduct.md
      - Contributing: STEMAIDE_CODER_Kit_Manual/Appendices/Contributing.md
      - Changelog: STEMAIDE_CODER_Kit_Manual/Appendices/Changelog.md
  - Glossary: STEMAIDE_CODER_Kit_Manual/Glossary/STEMAIDE_Glossary.md
  - References: STEMAIDE_CODER_Kit_Manual/References/References.md

