site_name: STEMAIDE Docs
site_description: Documentation for STEMAIDE, a platform for STEMAIDE Kit Manual.
site_url: https://docs.stemaide.com
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  primary: indigo
  accent: indigo
  favicon: assets/favicon.ico
  logo: assets/stemaide-logo-white-footer.128px.webp
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share  
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky.scroll.target: .md-header-nav
    - Core Features: features/core-features.md
    - Advanced Features: features/advanced-features.md
copyright: |
  <div style="display: flex; align-items: center; gap: 8px; font-size: 12px;">
    <img src="assets/stemaide-logo-white-footer.128px.webp" alt="STEMAIDE Logo" height="25px" width="25px"/>
    <span>© 2024 - 2025 STEMAIDE AFRICA</span>
  </div>
font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - tags
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
 
  - Guides:
      - User Guide: guides/user-guide.md
      - Beginner's Use Case: 1.0/version1.md
      - Intermediate Use Case: 2.0/version2.md
      - Advanced Use Case: 3.0/version3.md
      - Developer Guide: guides/developer-guide.md
  - Changelog: CHANGELOG.md
  - Contributing: CONTRIBUTING.md
  - About: about.md
  - Code of Conduct: code-of-conduct.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/whatsapp
      link: https://www.whatsapp.com/channel/0029VaCyaNN5a23vbdCABI0n
      name: Chat with us on WhatsApp
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/stemaideafrica
      name: STEMAIDE on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/stemaideafrica
      name: STEMAIDE on Instagram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/stemaideafrica
      name: STEMAIDE on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/stemaide-africa
      name: STEMAIDE on LinkedIn
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@stemaide?_t=ZM-8xaIGd6aIR6&_r=1
      name: STEMAIDE on TikTok
  generator: false
  homepage: /