site_name: STEMAIDE Docs
site_description: Documentation for STEMAIDE, a platform for STEMAIDE Kit Manual.
site_url: https://docs.stemaide.com


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      icon: material/weather-night
      name: Switch to dark mode 
      label: Toggle dark mode
    - scheme: slate
      toggle:
      icon: material/weather-sunny
      name: Switch to light mode 
      label: Toggle light mode
  logo: assets/stemaide-logo-white-footer.128px.webp   
  favicon: assets/favicon.ico 

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share  
    - navigation.footer
    - navigation.tabs.sticky.scroll.target: .md-header-nav
  copyright: Copyright &copy; 2024 - 2025 STEMAIDE AFRICA

  primary_color: '#4CAF50'
  font:
    text: Roboto
    code: Roboto Mono

  logo:
    text: STEMAIDE-logo
    image: assets/stemaide-logo-white-footer.128px.webp

  accent:
    text: '#FFFFFF'
    background: '#4CAF50'

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md

  - Features:
      - Core Features: features/core-features.md
      - Advanced Features: features/advanced-features.md

  - Guides:
      - User Guide: guides/user-guide.md
      - Beginner's Use Case: 1.0/version1.md
      - Intermediate Use Case: 2.0/version2.md
      - Advanced Use Case: 3.0/version3.md
      - Developer Guide: guides/developer-guide.md 

  - Changelog: changelog.md
  - Contributing: contributing.md
  - About: about.md
  - Code of Conduct: code-of-conduct.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      use_pygments: true
  
extra:
  generator: false
  homepage: /


